version: "3"

services:
  python_app:
    image: artsemyeuroman/trgtest:hello_world
    ports:
      - 8080:8080

  nginx-proxy:
    image: nginx
    ports:
      - 80:80
    volumes:
      -  /etc/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - python_app

