version: "3"

services:
  python_app:
    image: artsemyeuroman/helloworld:v1
    ports:
      - 8080:8080
    networks:
      - backend


  nginx-proxy:
    image: nginx
    ports:
      - 80:80
    volumes:
      -  /etc/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - python_app
    networks:
      - backend

networks:
  backend:


